# ********************** COPYRIGHT INTEL CORPORATION ***********************
#
# THE SOFTWARE CONTAINED IN THIS FILE IS CONFIDENTIAL AND PROPRIETARY
# TO INTEL CORPORATION. THIS PRINTOUT MAY NOT BE PHOTOCOPIED,
# REPRODUCED, OR USED IN ANY MANNER WITHOUT THE EXPRESSED WRITTEN
# CONSENT OF INTEL CORPORATION. ALL LOCAL, STATE, AND FEDERAL
# LAWS RELATING TO COPYRIGHTED MATERIAL APPLY.
#
# Copyright (c), Intel Corporation
#
# ********************** COPYRIGHT INTEL CORPORATION ***********************


from constants.datasheetconstants import DATASHEET_TITLE_FIELD, DATASHEET_DESCRIPTION_FIELD, DATASHEET_INPUT_FILE_FIELD, DATASHEET_GUID_FIELD,\
    DATASHEET_CREATION_DATE_FIELD

INITIAL_SHEET = "ReadMe"
HEADER_DATASHEET_LIST = [DATASHEET_TITLE_FIELD, DATASHEET_DESCRIPTION_FIELD,
                         DATASHEET_INPUT_FILE_FIELD, DATASHEET_GUID_FIELD, DATASHEET_CREATION_DATE_FIELD]
