from constants.datasheetconstants import DATASHEET_TITLE_FIELD, DATASHEET_DESCRIPTION_FIELD, DATASHEET_INPUT_FILE_FIELD, DATASHEET_GUID_FIELD, \
    DATASHEET_CREATION_DATE_FIELD

INITIAL_SHEET = "ReadMe"
HEADER_DATASHEET_LIST = [DATASHEET_TITLE_FIELD, DATASHEET_DESCRIPTION_FIELD,
                         DATASHEET_INPUT_FILE_FIELD, DATASHEET_GUID_FIELD, DATASHEET_CREATION_DATE_FIELD]
