# ********************** COPYRIGHT INTEL CORPORATION ***********************
#
# THE SOFTWARE CONTAINED IN THIS FILE IS CONFIDENTIAL AND PROPRIETARY
# TO INTEL CORPORATION. THIS PRINTOUT MAY NOT BE PHOTOCOPIED,
# REPRODUCED, OR USED IN ANY MANNER WITHOUT THE EXPRESSED WRITTEN
# CONSENT OF INTEL CORPORATION. ALL LOCAL, STATE, AND FEDERAL
# LAWS RELATING TO COPYRIGHTED MATERIAL APPLY.
#
# Copyright (c), Intel Corporation
#
# ********************** COPYRIGHT INTEL CORPORATION ***********************


"""
Difference Constants
"""

PLUGIN = 'diff'
PLUGIN_DESC = "Diff Analysis"
PLUGIN_ARGUMENT = "--diff"
PLUGIN_ARGUMENT_FILE1 = "--diff1"
PLUGIN_ARGUMENT_FILE2 = "--diff2"

DIFF_HELP_ARGUMENT = 'Compare 2 datasheets'
DIFF1_HELP_ARGUMENT = 'First file to compare'
DIFF2_HELP_ARGUMENT = 'Second file to compare'

PLUGIN_REPORT_DESCRIPTION = "Digital Datasheets Difference Report"

PLUGIN_TYPE_OUTPUT_DESIGNATOR = "-diff"

PLUGINARGUMENT = "--diff"
