# ********************** COPYRIGHT INTEL CORPORATION ***********************
#
# THE SOFTWARE CONTAINED IN THIS FILE IS CONFIDENTIAL AND PROPRIETARY
# TO INTEL CORPORATION. THIS PRINTOUT MAY NOT BE PHOTOCOPIED,
# REPRODUCED, OR USED IN ANY MANNER WITHOUT THE EXPRESSED WRITTEN
# CONSENT OF INTEL CORPORATION. ALL LOCAL, STATE, AND FEDERAL
# LAWS RELATING TO COPYRIGHTED MATERIAL APPLY.
#
# Copyright (c), Intel Corporation
#
# ********************** COPYRIGHT INTEL CORPORATION ***********************


TOPIC_REF_TAG = "topicref"
TOPIC_META_TAG = "topicmeta"
NAV_TITLE_TAG = "navtitle"

DOCUMENT_TYPE = "E-Datasheet Map"

HREF_ATTRIBUTE = "href"
FORMAT_ATTRIBUTE = "format"
NAV_TITLE_ATTRIBUTE = "navtitle"
TYPE_ATTRIBUTE = "type"
ID_ATTRIBUTE = "id"

TOPIC_TYPE = "topic"
DITA_FORMAT = "dita"


REFERENCE_KEY = "reference"
TITLE_KEY = "name"
CHILDREN_KEY = "children"
PARENT_KEY = "parent"
PREDECESSORS_KEY = "predecessors"
GUID_KEY = "guid"

TREE_KEY = "tree"

DITAMAP_EXT = ".ditamap"
