"""
Header constants for JSON file
"""

DATASHEET = "datasheet"
DATA = "data"
TITLE = "title"
INPUT_FILE = "inputFile"
GENERATED_BY = "generatedBy"
GENERATED_ON = "generatedOn"
PLATFORM_ABBREVIATION = "platformAbbreviation"
DESCRIPTION = "description"
SKU = "sku"
VERSION = "version"
GUID = "guid"
DOCUMENT_TYPE = "document_type"
REVISION = "revision"
COLLATERAL = "collateral"
NAMESPACE = "namespace"
