# ********************** COPYRIGHT INTEL CORPORATION ***********************
#
# THE SOFTWARE CONTAINED IN THIS FILE IS CONFIDENTIAL AND PROPRIETARY
# TO INTEL CORPORATION. THIS PRINTOUT MAY NOT BE PHOTOCOPIED,
# REPRODUCED, OR USED IN ANY MANNER WITHOUT THE EXPRESSED WRITTEN
# CONSENT OF INTEL CORPORATION. ALL LOCAL, STATE, AND FEDERAL
# LAWS RELATING TO COPYRIGHTED MATERIAL APPLY.
#
# Copyright (c), Intel Corporation
#
# ********************** COPYRIGHT INTEL CORPORATION ***********************


"""
HTML Constants
"""
HTML_H1_TAG = 'h1'
HTML_H2_TAG = 'h2'
HTML_TITLE_TAG = 'title'
HTML_TABLE_TAG = "table"
HTML_TABLE_HEADER_TAG = "th"
HTML_TABLE_ROW_TAG = "tr"
HTML_TABLE_ROW_DATA_TAG = "td"
HTML_PARAGRAPH_TAG = "p"

# Table wrapper class
HTML_TABLE_WRAPPER = "wrapper page"

# Plugin constants
HTML_TITLE = "title"
HTML_DESCRIPTION = "description"
HTML_INPUT_FILE = "inputFile"
HTML_GUID = "guid"
HTML_CREATED_ON = "createdOn"


# Table types
NO_VALID_TABLE_TYPE = 0
SUMMARY_TABLE_TYPE = 1
DATA_TABLE_TYPE = 2
