# Spreadsheet map field name constants

POWERPOINT_MAP_DESCRIPTION_FIELD = 'description'
POWERPOINT_MAP_MAPTYPE_FIELD = 'mapType'
POWERPOINT_MAP_GUID_FIELD = 'guid'
POWERPOINT_MAP_SLIDEDETAILS_FIELD = 'slideDetails'
