# ********************** COPYRIGHT INTEL CORPORATION ***********************
#
# THE SOFTWARE CONTAINED IN THIS FILE IS CONFIDENTIAL AND PROPRIETARY
# TO INTEL CORPORATION. THIS PRINTOUT MAY NOT BE PHOTOCOPIED,
# REPRODUCED, OR USED IN ANY MANNER WITHOUT THE EXPRESSED WRITTEN
# CONSENT OF INTEL CORPORATION. ALL LOCAL, STATE, AND FEDERAL
# LAWS RELATING TO COPYRIGHTED MATERIAL APPLY.
#
# Copyright (c), Intel Corporation
#
# ********************** COPYRIGHT INTEL CORPORATION ***********************


"""
Transformer constants for DITA Files and others
"""

TRANSFORMER_CONFIGURATION_DESC = "Transformer Configuration"
GENERATED_BY = "Intel e-Datasheet Generator"

TABLE_ENTRIES = "table_entries"
TABLE_ATTRIBUTES = "table_attributes"
TABLE_ATTRIBUTES_TYPE = "type"
TABLE_ATTRIBUTES_SEPARATOR = "separator"
TABLES_CONTAINER = "tables"
IMAGES = "images"
ATTACHMENTS = "attachments"
ATTACHMENT_REFERENCE = "reference"
ATTACHMENT_TYPE = "type"
ATTACHMENT_NAME = "name"

NOT_FOUND = "N/A"
EMPTY = "Empty"
UNKNOWN = "Unknown"
FAILED = "FAILED"

NOTES = "notes"
NOTE = "note"

ATTRIBUTES_SEPARATOR = ","
ATTRIBUTES_KEY_VALUE_SEPARATOR = ":"
TITLE_SEPARATOR = ","
